import Head from 'next/head'
import Image from 'next/image'
import Home from "./home"
import Header from "../components/layout/Header"

export default function Index() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Home/>
    </div>
  )
}
